[package]
name = "py_index"
version = "2025.2.15"
edition = "2021"

[lib]
name = "py_index"
path = "py_index/src/rs/lib.rs"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[[bin]]
name = "main"
path = "py_index/src/rs/main.rs"

[dependencies]
rand = "0.9.0"
pyo3 = { version = "0.25.0", features = ["extension-module"] }
ahash = "0.8.12"
ordered-float = "5.0.0"
